version: "3"
services:
  app:
    container_name: dotlov3
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3334:3333"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/database_name
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database_name
