version: '3'
services:
  app:
    container_name: dotlov3
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /usr/src/app/node_modules
    ports:
      - '3334:3333'
    command: bash -c "npm install && npm run migrate && npm run start"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - PG_DATA: /var/lib/postgresql/data
    volumes:
      - pgdata:/var/lib/postgresql/data
